# @Author       : Gainovel
# @Organization : Copyright © 2023-2024 gainovel.com All Rights Reserved.
# @Date         : 2024-01-16 18:00:53 星期二
# @ProductName  : GoLand
# @PrjectName   : u-dai-server
# @File         : /Makefile
# @Version      : v0.1.0
# @Description  : 开发中···

.PHONY: grpc
grpc:
	@buf generate api/proto
